import katex from "katex"
import type { FC } from "react"

export const InlineMath: FC<{ tex: string; className?: string }> = ({ tex, className }) => {
  const html = katex.renderToString(tex, { throwOnError: false })

  // biome-ignore lint/security/noDangerouslySetInnerHtml: This is a trusted source generated by KaTeX
  return <span className={className} dangerouslySetInnerHTML={{ __html: html }} />
}

export const BlockMath: FC<{ tex: string; className?: string }> = ({ tex, className }) => {
  const html = katex.renderToString(tex, { throwOnError: false })

  // biome-ignore lint/security/noDangerouslySetInnerHtml: This is a trusted source generated by KaTeX
  return <div className={className} dangerouslySetInnerHTML={{ __html: html }} />
}
